package com.dage.recruit.dto;

import lombok.Data;

@Data
public class EducationFormDTO {
    private long seq;
    private String h1Sdt;
    private String h1Edt;
    private String h105;
    private String h106;
    private String h107;
    private String h108;
    private String h2Sdt;
    private String h2Edt;
    private String h205;
    private String h206;
    private String h207;
    private String h208;
    private String h209;
    private String h210;
    private String h211;
    private String h212;
    private String h213;
    private String h214;
    private String h3Sdt;
    private String h3Edt;
    private String h305;
    private String h306;
    private String h307;
    private String h308;
    private String h309;
    private String h310;
    private String h311;
    private String h312;
    private String h313;
    private String h314;
    private String h4Sdt;
    private String h4Edt;
    private String h405;
    private String h406;
    private String h407;
    private String h408;
    private String h409;
    private String h410;
    private String h411;
    private String h412;
    private String h413;
    private String h414;
    private String h5Sdt;
    private String h5Edt;
    private String h505;
    private String h506;
    private String h507;
    private String h508;
    private String h509;
    private String h510;
    private String h511;
    private String h512;
    private String h513;
    private String h514;
    private String h515;
    private String h6Sdt;
    private String h6Edt;
    private String h605;
    private String h606;
    private String h607;
    private String h608;
    private String h609;
    private String h610;
    private String h611;
    private String h612;
    private String h613;
    private String h614;
    private String h615;
}
